 version: '3.3'

 services:
   # Postgres
   db:
     image: postgres
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=liquida2020

   web:
     build: .
     #command: ["./run_web.sh"]
     command: bash -c "chmod +x run_web.sh
          && ./run_web.sh"
     volumes:
       - .:/webapps
     ports:
       - "8000:8000"
     links:
       - db
     depends_on:
       - db
