# Generated by Django 3.2.20 on 2024-06-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdesaoLojista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(help_text='ex. 00.000.000/0000-00', max_length=18, null=True, unique=True, verbose_name='Cnpj do Lojista')),
                ('razao_social', models.CharField(max_length=250, null=True, verbose_name='Razão Social')),
                ('fantasia', models.CharField(max_length=250, null=True, verbose_name='Nome Fantasia')),
                ('email', models.EmailField(max_length=250, null=True, verbose_name='Email')),
                ('telefone', models.CharField(help_text='(xx) xxxxx - xxxx', max_length=20, null=True, verbose_name='Telefone')),
                ('data_contato', models.DateTimeField(blank=True, help_text='Data e hora em que o vendedor entrou em contato ', null=True, verbose_name='Data do contato')),
            ],
            options={
                'verbose_name': 'Adesão de Lojista',
                'verbose_name_plural': 'Adesões de Lojistas',
            },
        ),
    ]
