# Generated by Django 3.2.20 on 2024-06-13 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lojista', '0003_adesaolojista_atendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='adesaolojista',
            name='atendido_por',
            field=models.ForeignKey(blank=True, help_text='Atendido por', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
