# Generated by Django 3.2.20 on 2024-06-17 12:54

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lojista', '0006_rename_localizacao_lojista_localizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizacao',
            name='CadastradoPor',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por'),
        ),
    ]
