# Generated by Django 3.2.20 on 2023-08-25 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('participante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCriacao', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
                ('impresso', models.BooleanField(default=False)),
                ('dataImpressao', models.DateTimeField(null=True)),
                ('documentoFiscal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='rel_cupom_doc', to='participante.documentofiscal')),
                ('operador', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_cupom_operador', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_cupom_participante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
