# Generated by Django 3.2.20 on 2024-06-16 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0003_auto_20240616_2053'),
        ('cupom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='posto_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='participante.postotrabalho'),
        ),
    ]
