# Generated by Django 3.2.20 on 2024-07-09 01:53

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cupom', '0002_cupom_posto_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='operador',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_cupom_operador', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por'),
        ),
    ]
