# Generated by Django 3.2.20 on 2024-06-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofiscal',
            name='compradoMASTERCARD',
            field=models.BooleanField(default=False, verbose_name='Comprou com Elo?'),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='compradoREDE',
            field=models.BooleanField(default=False, verbose_name='Comprou na maquininha da PagBank?'),
        ),
    ]
