# Generated by Django 3.2.20 on 2024-06-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0002_auto_20240613_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='compradoREDE',
            field=models.BooleanField(default=False, verbose_name='Comprou na maquininha da PagBank ou pagou com Elo?'),
        ),
    ]
