# Generated by Django 3.2.20 on 2024-06-18 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0005_profile_posto_de_trabalho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='posto_de_trabalho',
            new_name='posto_trabalho',
        ),
    ]
