# Generated by Django 3.2.20 on 2024-06-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0007_alter_documentofiscal_compradorede'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='pendente_01',
            field=models.BooleanField(default=True, verbose_name='Pendente'),
        ),
    ]
