# Generated by Django 3.2.20 on 2024-06-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0008_documentofiscal_pendente_01'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentofiscal',
            name='pendente_01',
        ),
    ]
