# Generated by Django 3.2.20 on 2024-06-19 15:36

from django.db import migrations, models
import participante.models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0009_remove_documentofiscal_pendente_01'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='enviado_por_operador',
            field=models.BooleanField(default=False, verbose_name='Enviado por operador'),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='dataDocumento',
            field=models.DateField(validators=[participante.models.validate_promotional_period], verbose_name='Data do Documento'),
        ),
    ]
