# Generated by Django 3.2.20 on 2024-06-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0010_auto_20240619_1236'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentofiscal',
            constraint=models.UniqueConstraint(fields=('user', 'numeroDocumento', 'lojista'), name='unique_user_numeroDocumento_lojista'),
        ),
    ]
