# Generated by Django 3.2.20 on 2024-06-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0011_documentofiscal_unique_user_numerodocumento_lojista'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='documentofiscal',
            name='unique_user_numeroDocumento_lojista',
        ),
        migrations.AddConstraint(
            model_name='documentofiscal',
            constraint=models.UniqueConstraint(fields=('numeroDocumento', 'lojista'), name='unique_user_numeroDocumento_lojista'),
        ),
    ]
